### ISSUE TITLE
Values duplicated for 2020-03-23

### ISSUE THREAD

**Issue by wjholst** [imdevskp/covid_19_jhu_data_web_scrap_and_cleaning#2]
Not sure of the relationship of this extract to the Kaggle dataset, but the Kaggle values for 2020-03-23 are the same as the previous day, I think for all rows.

**Comment by Philliec459** [comment]
Yes please. The 3/23 numbers are the same as 3/22. That would be great to have zero change in Confirmed...., but not reasonable for every country.

**Comment by avinashbhat** [comment]
It seems the upstream URLs are deprecated, which is probably the issue.
![image](https://user-images.githubusercontent.com/16733513/77503417-89ce6f00-6e83-11ea-8715-5861fea6dbaa.png)
