### ISSUE TITLE
Data Update

### ISSUE THREAD

**Issue by rogeraleite** [imdevskp/covid_19_jhu_data_web_scrap_and_cleaning#4]
Could you please update the data or add instructions in the readme file that I could use to update that?

**Comment by imdevskp** [comment]
Data is update. Code used to scrap the data is within the repository 

https://github.com/imdevskp/covid_19_jhu_data_web_scrap_and_cleaning/blob/master/worldometer_site_web_scrapping.ipynb

https://github.com/imdevskp/covid_19_jhu_data_web_scrap_and_cleaning/blob/master/data_cleaning.ipynb
